/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RouteConfig } from "./components/micro-container/models/route-config.model";
import { AppLink } from "./components/micro-link/models";
export namespace Components {
    interface DevbMicroContainer {
        "navigate": (appName: string, path?: string) => Promise<void>;
        /**
          * Micro frontend routing configuration, used to identify applications and their urls. NOTE: Micro Application URLs must be on same domain, or you have to disable browser security to run in different domain on local environment.
         */
        "routeConfig": RouteConfig[];
    }
    interface DevbMicroLink {
        /**
          * Application name configured in Route Config property.
         */
        "appName": string;
        /**
          * If Link is clicked from child application.
         */
        "isChild": boolean;
        /**
          * If link is external, it will try to navigate from parent.
         */
        "isExternal": boolean;
        /**
          * Path of the page within the application, relative to application domain.
         */
        "path": string;
    }
}
declare global {
    interface HTMLDevbMicroContainerElement extends Components.DevbMicroContainer, HTMLStencilElement {
    }
    var HTMLDevbMicroContainerElement: {
        prototype: HTMLDevbMicroContainerElement;
        new (): HTMLDevbMicroContainerElement;
    };
    interface HTMLDevbMicroLinkElement extends Components.DevbMicroLink, HTMLStencilElement {
    }
    var HTMLDevbMicroLinkElement: {
        prototype: HTMLDevbMicroLinkElement;
        new (): HTMLDevbMicroLinkElement;
    };
    interface HTMLElementTagNameMap {
        "devb-micro-container": HTMLDevbMicroContainerElement;
        "devb-micro-link": HTMLDevbMicroLinkElement;
    }
}
declare namespace LocalJSX {
    interface DevbMicroContainer {
        /**
          * Micro frontend routing configuration, used to identify applications and their urls. NOTE: Micro Application URLs must be on same domain, or you have to disable browser security to run in different domain on local environment.
         */
        "routeConfig"?: RouteConfig[];
    }
    interface DevbMicroLink {
        /**
          * Application name configured in Route Config property.
         */
        "appName"?: string;
        /**
          * If Link is clicked from child application.
         */
        "isChild"?: boolean;
        /**
          * If link is external, it will try to navigate from parent.
         */
        "isExternal"?: boolean;
        /**
          * Event emitted when link is clicked. Value would be path.
         */
        "onLinkClicked"?: (event: CustomEvent<AppLink>) => void;
        /**
          * Path of the page within the application, relative to application domain.
         */
        "path"?: string;
    }
    interface IntrinsicElements {
        "devb-micro-container": DevbMicroContainer;
        "devb-micro-link": DevbMicroLink;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "devb-micro-container": LocalJSX.DevbMicroContainer & JSXBase.HTMLAttributes<HTMLDevbMicroContainerElement>;
            "devb-micro-link": LocalJSX.DevbMicroLink & JSXBase.HTMLAttributes<HTMLDevbMicroLinkElement>;
        }
    }
}
